url: http://yuanyong.org/zh-case-studies/
pygments: true
markdown: redcarpet
exclude: ['README.md', 'railstutorial-china.sublime-project', 'railstutorial-china.sublime-workspace', 'Gemfile', 'Gemfile.lock', 'CONTRIBUTING.md']
